### ISSUE TITLE
rsync issues when running git-cvs

### ISSUE THREAD

**Issue by Stevecosoft** [osamuaoki/git-cvs#1]
I had a couple of issues when git-cvs called rsync:
1. my username on the CVS server is different from my username on my development machine
2. rsync was stopping with errors because it couldn't access hidden files and directories in /home/CVS, for example /home/CVS/.ssh

To work around this I changed all the rync commands to look like

```
rsync -avS --exclude=".*" --exclude ".*/" --delete --delay-updates -e "ssh -l mycvsusername" --rsh=ssh mycvsusername@cvsservername:/home/CVS/. rsyncdir
```

**Comment by osamuaoki** [comment]
Please read "man ssh" to set up ~/.ssh/config.

Host cvsservername
  User mycvsusername

or export an environment variable USER to set the name at the remote site
